//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraCaso
    {
        public int idBitacora { get; set; }
        public int idUsuario { get; set; }
        public int tipoMovimiento { get; set; }
        public System.DateTime fecha { get; set; }
        public int idCaso { get; set; }
        public int idPersona { get; set; }
        public int usuario { get; set; }
        public int idEstado { get; set; }
        public int tipoLitigante { get; set; }
        public int numeroCaso { get; set; }
        public string materia { get; set; }
        public string descripcion { get; set; }
        public string observacion { get; set; }
        public string observacionBitacora { get; set; }
    
        public virtual TablaGeneral TablaGeneral { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
