//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraDocumento
    {
        public int idBitacora { get; set; }
        public int idUsuario { get; set; }
        public int tipoMovimiento { get; set; }
        public System.DateTime fecha { get; set; }
        public int idDocumento { get; set; }
        public int idTipo { get; set; }
        public int idOrigen { get; set; }
        public int tipoOrigen { get; set; }
        public Nullable<int> idEstado { get; set; }
        public Nullable<long> idReferencia { get; set; }
        public string numeroDocumento { get; set; }
        public string numeroIngreso { get; set; }
        public System.DateTime fechaDocumento { get; set; }
        public string asunto { get; set; }
        public string descripcion { get; set; }
        public string ubicacion { get; set; }
        public string observacion { get; set; }
        public string observacionBitacora { get; set; }
    
        public virtual TablaGeneral TablaGeneral { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
