//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SCJ_BDEntities : DbContext
    {
        public SCJ_BDEntities()
            : base("name=SCJ_BDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adjunto> Adjuntos { get; set; }
        public virtual DbSet<BitacoraCaso> BitacoraCasos { get; set; }
        public virtual DbSet<BitacoraDestinatario> BitacoraDestinatarios { get; set; }
        public virtual DbSet<BitacoraDocumento> BitacoraDocumentos { get; set; }
        public virtual DbSet<BitacoraPersona> BitacoraPersonas { get; set; }
        public virtual DbSet<Caso> Casos { get; set; }
        public virtual DbSet<Destinatario> Destinatarios { get; set; }
        public virtual DbSet<Documento> Documentos { get; set; }
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<TablaGeneral> TablaGenerals { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
